# -*- coding: utf-8 -*-
"""AnaliseExploratoriaDados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LAUZ4lrCPj9Gd089o_UQKy8OKpmuy5dQ
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

plt.style.use("seaborn-v0_8-whitegrid")

plt.rcParams['figure.figsize']  = (16, 10)
plt.rcParams['axes.labelsize']  = 20
plt.rcParams['axes.titlesize']  = 20
plt.rcParams['legend.fontsize'] = 20
plt.rcParams['xtick.labelsize'] = 20
plt.rcParams['ytick.labelsize'] = 20
plt.rcParams['lines.linewidth'] = 4
plt.ion()

def despine(ax=None):
    if ax is None:
        ax = plt.gca()
    # Esconder linhas curvadas a esquerda e acima
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)

    # mostrar marcas a esquerda a linhas curvadas abaixo
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')

path = "/content/drive/MyDrive/especialidades.xlsx"
df = pd.read_excel(path)
df.columns = ['ambulatorio', 'jul', 'ago', 'set', 'out', 'nov', 'dez', 'total']
df = df[['ambulatorio', 'jul', 'ago', 'set', 'out','nov', 'dez', 'total']]
df = df.dropna()
df.count()
df.head()

print(df.dtypes)
print(df.describe())

meses = ['jul', 'ago', 'set', 'out','nov', 'dez']
df['total'] = pd.to_numeric(df['total'], errors='coerce')

# Crie um histograma com as colunas selecionadas

data = df.iloc[:-1]['total'].dropna()
data.shape

plt.hist(data, bins=20, edgecolor='k')
plt.xlabel('Total atendimentos especializado')
plt.ylabel('Frequência.')
despine(plt.gca())
plt.show()

def ecdf(data):
    x = np.sort(data)
    count = np.arange(len(data))
    y = count.cumsum()
    y = y / y.max()
    return x, y

x, y = ecdf(data)
plt.plot(x, y)
plt.xlabel('Total atendimentos especializados')
plt.ylabel('$P(X \leq x)$')
despine()
plt.show()

data.head()

num_points = len(data)
print("número de pontos:", num_points)

maiorTotalAtendimento = max(data) 
menorTotalAtendimento = min(data)
print("máximo: ", maiorTotalAtendimento, "\nminimo: ", menorTotalAtendimento)

def mean(x):
    return sum(x) / len(x)

print("média: ", mean(data))

plt.hist(data, bins=20, label='PDF', edgecolor='k')
plt.vlines(data.mean(), 0, 10, label='Mean', edgecolor='k')
plt.xlabel('Total atendimentos especializados')
plt.ylabel('P(X = x)')
plt.legend()
despine()
plt.show()

print("Mediana: ", np.median(data))

plt.hist(data, bins=20, label='Freq.', edgecolor='k')
plt.vlines(data.mean(), 0, 10, label='Mean', edgecolor='k')
plt.vlines(data.median(), 0, 10, linestyles='--', label='Median', color='red')
plt.xlabel('Duração em minutos')
plt.ylabel('Freq')
plt.legend()
despine()
plt.show()

def mode(x):
    x = np.asanyarray(x)
    unique, counts = np.unique(x, return_counts=True)
    max_count = counts.max()
    return unique[counts == max_count]

print("Moda do total de atendimentos: ", mode(np.round(data, 0)))

def data_range(x):
    return max(x) - min(x)

print("range: ", data_range(data))

def de_mean(x):
    """translada x subtraindo sua média (então o resultado tem média 0)"""
    x_bar = mean(x)
    return [x_i - x_bar for x_i in x]

def variance(x):
    """assume que x tem pelo menos dois elementos"""
    n = len(x)
    deviations = de_mean(x)
    deviations = np.array(deviations) #vamos usar numpy muito de agora em diante
    return np.sum(deviations ** 2) / (n-1)
    #voce pode usar a funcao que implementamos anteriormente:
    #return sum_of_squares(deviations) / (n - 1)

print("variância: ", variance(data))
print("desvio padrão: ", np.std(data))

data.describe()